apiVersion: v1
kind: Secret
metadata:
    name: regcred
type: kubernetes.io/dockerconfigjson
data:
    .dockerconfigjson: ENC[AES256_GCM,data:B26UGF/HY4f1I4DT/Yd5Ndvh3S9Pr2rTy3Lop9u2ejAuYe9GBc0o46RUydHE+AILcqwwXB3e25lUyeux3aGGKmtM07J5Og9eAUT7OpFOV35BNrlIaX3G+pQOTFj7y41YjfQu2YUsrpqXf3lEmGjBKNpMIU44svk33rp6+13YnTIhKo5eOFJEBVWqjJ3d1epK2rkz4t8L1q9XYQqKIvH1mCR+NzaMsC5xofaQNPmmRQkXcxxp7p/2FAeyuK2jqSWmBD2Hb5vORlTF8dH68s/xfyvi29fNcCyOtScDBxaDCSkC6YYMkrqDBnFBpSaZghHR,iv:ws9TjmRptTzVED9oePTqqDh78Fyis7sHtHBpuOPk9qA=,tag:WzRNlXN+ONA49D0vyZzHBA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1cckx776gked35l005asl5mzdygmqds4tw5xka9jtf0wtdj3kfyrspk5mg4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoR29XTE80b3Q3RE9kWjc0
            MGo0eDZaMDNQcHZGSXlBbCtWQkZUZ21rWEhzCmJFRlNzS21ibWtuUHVVa24vT3M3
            T2d2dk9HSldvak1GZk55NCtnaTA0WHMKLS0tIHFPYW04c2NJNVMvRzg2dEN0WjU4
            Y1djaVlWR1JvZWNkcHM0TzRzL1pvMGcKykR5FxqnPCEeSLf11w2lOvEFL+upfMEL
            8RFAhJTICaeK0iVr5Q/vbIfQFishiFBQ24zmzbbecOtIkZXndzFAkw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-04T13:08:27Z"
    mac: ENC[AES256_GCM,data:jcQmCqh0Tdp41m2L21qDfYuEoDz+CB8DExKnTxUn4WFygc2BNdWmGB7gcD1kW1hmxFrnLyz1wW+NdnkkOIr6amrn5CuFOBoE8F8S0JqrxfUAlOqk7SCPdTxEFbkIUQG9n48aBLIbBTcJas+Zzp2pizoCr/GweNbcth9Tu1BQTr0=,iv:7ubGJWLLywVqH3f1se3GeP/QMRE9JGxAcDwpHHSBli4=,tag:tc2DwjRzw0dYgTUOcfZxBw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
