apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: api
  namespace: flux-system
spec:
  image: registry.digitalocean.com/studidevops-sukma/books-api
  interval: 1m
  secretRef:
    name: regcred