apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: api
spec:
  imageRepositoryRef:
    name: api
  filterTags:
    pattern: '^[0-9]+$'
  policy:
    numerical:
      order: asc