apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: ingress-nginx
spec:
  interval: 5m0s
  url: https://kubernetes.github.io/ingress-nginx

  # helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
  # helm install ingress-nginx ingress-nginx/ingress-nginx