apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: consul
  namespace: core
spec:
  chart:
    spec:
      chart: bitnami/consul
      version: 11.3.16
      sourceRef:
        kind: HelmRepository
        name: hashicorp
        namespace: flux-system
  interval: 5m
  values:
    global:
      name: consul
      datacenter: dc1
      enableGossipEncryption: true
    server:
      replicas: 3
    ui:
      enabled: true
