---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Provider
metadata:
  name: discord-provider
  namespace: flux-system
spec:
  channel: cd-notif
  secretRef:
    name: discord-url
  type: discord
