apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: cert-manager

resources:
  - namespace.yaml
  - ../../../../modules/helm/cert-manager/helm-repository.yaml
  - release.yaml
  - issuer.yaml