apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: api
        image: registry.digitalocean.com/studidevops-sukma/books-api:7 # {"$imagepolicy": "flux-system:api"}
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
          requests:
            memory: "64Mi"
            cpu: "100m"
        ports:
        - containerPort: 8080
        env:
        - name: ENVIRONMENT
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: ENVIRONMENT
        - name: POSTGRES_CONN
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: POSTGRES_CONN
