apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: api
        image: registry.digitalocean.com/studidevops-sukma/books-api:4
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
          requests:
            memory: "64Mi"
            cpu: "100m"
        ports:
        - containerPort: 8080
        env:
          - name: CONSUl_ADDRESS
            valueFrom:
              secretKeyRef:
                name: consul-secret
                key: CONSUl_ADDRESS

