apiVersion: v1
kind: Secret
metadata:
    name: consul-secret
type: Opaque
data:
    CONSUL_ADDRESS: ENC[AES256_GCM,data:3FEjs6r3gcMNU9IhnqHNreY=,iv:L+pVluQhWgF9L42/2DO/GdK56XfWvae47jiXAU4DEb8=,tag:MP0wLneFJDpaasaA8qrIvg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1cckx776gked35l005asl5mzdygmqds4tw5xka9jtf0wtdj3kfyrspk5mg4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwVjBWY1ZBeWRLejNUcmtY
            YTAwb1NCR2kxbHZMb1RMWE1YWXZHdDhvcFNjClVhZTNmOTFwZjA1UVB0Y20rTkdj
            UnltNHBwYnYyOUUzdUN3a0VadGdZUGsKLS0tIEVVenRsb05EcWVadkRoMUdtWHRu
            Ync0OXBDOXZqV2xDRHdEdmpCNEtFSFEKBKhqfzcytV73K8DE9N80uJgUCbkyyXMM
            TkjlzQLLCOTUgH7AgU9SKAeAOZ22AWoBy/DnMNxUOuWs7N6OjMxSGA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-04T15:05:34Z"
    mac: ENC[AES256_GCM,data:6YXil6S51ovzkVygRZ6XAfM99GKGjGchW/2W10/kQYaYRwV72Qh8gKFxImLHCswynL7IbxBoY+AA0eKrZ4MKepN/SrY8qnbFaRlvSqkdM36eUg5KxfniBfjzYa+4m921RxXV5J+ANyFxZ0esgkdOiBq8FbtMVb0XdtvQMegd7f8=,iv:5DPRUck/IjB41QerPwkOv8oTqaJAy3Bb01t+6cxaKJs=,tag:jK8tWsMNK2QvyHb5s/ilqg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
