apiVersion: v1
kind: Secret
metadata:
    name: app-secret
type: Opaque
data:
    ENVIRONMENT: UFJPRFVDVElPTgo=
    POSTGRES_CONN: cG9zdGdyZXNxbDovL2Jvb2s6QVZOU19EeXpmczRYWHFBNzN6dG5NZ0JVQGRiLXBvc3RncmVzcWwtZG8tdXNlci0xNzgyNzkxNC0wLmQuZGIub25kaWdpdGFsb2NlYW4uY29tOjI1MDYwL2Jvb2tfZGI/c3NsbW9kZT1yZXF1aXJl
