apiVersion: v1
kind: Secret
metadata:
    name: app-secret
type: Opaque
data:
    POSTGRES_CONN: cG9zdGdyZXNxbDovL2RvYWRtaW46QVZOU19Gb0Q0anBDczZ0QURaNExpTWlBQGRiLXBvc3RncmVzcWwtZG8tdXNlci0xNzgyNzkxNC0wLmQuZGIub25kaWdpdGFsb2NlYW4uY29tOjI1MDYwL2Jvb2tfZGI/c3NsbW9kZT1yZXF1aXJl
