apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: proxy
  template:
    metadata:
      labels:
        app: proxy
    spec:
      containers:
      - name: proxy
        image: nginxinc/nginx-unprivileged:stable-alpine-slim
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
          requests:
            memory: "10Mi"
            cpu: "10m"
        ports:
        - containerPort: 80
