apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus
  namespace: monitoring
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: prometheus-community
      sourceRef:
        kind: HelmRepository
        name: prometheus
      interval: 5m
  releaseName: prometheus
  values:
    persistence:
      type: pvc
      enabled: true