apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-secret
  namespace: core
  labels:
    app: postgres
data:
  POSTGRES_DB: Ym9va19kYgo=
  POSTGRES_USER: Ym9vawo=
  POSTGRES_PASSWORD: Ym9vawo=