apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-volume
  namespace: core
  labels:
    type: local
    app: postgres
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/postgresql
