apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dummy
  template:
    metadata:
      labels:
        app: dummy
    spec:
      containers:
      - name: dummy
        image: nginx:alpine
        resources:
          limits:
            memory: "128mi"
            cpu: "100m"
          requests:
            memory: "10Mi"
            cpu: "10m"
        ports:
        - containerPort: 80
