apiVersion: v1
kind: Service
metadata:
  name: product
spec:
  type: ExternalName
  externalName: product.core.svc
---
apiVersion: v1
kind: Service
metadata:
  name: transaction
spec:
  type: ExternalName
  externalName: transaction.core.svc
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: product
  labels:
    name: product
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - product.setyaji.my.id
    - transaction.setyaji.my.id
    secretName: app-tls
  rules:
  - host: product.setyaji.my.id
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: product
            port: 
              number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: transaction
  labels:
    name: transaction
spec:
  ingressClassName: nginx
  rules:
  - host: transaction.setyaji.my.id
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: transaction
            port: 
              number: 80
