apiVersion: v1
kind: Service
metadata:
  name: product
spec:
  type: ExternalName
  externalName: product.core.svc
---
apiVersion: v1
kind: Service
metadata:
  name: transaction
spec:
  type: ExternalName
  externalName: transaction.core.svc
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
spec:
  type: ExternalName
  externalName: grafana.monitoring.svc
---
apiVersion: v1
kind: Service
metadata:
  name: consul
spec:
  type: ExternalName
  externalName: consul.consul.svc
---
apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  type: ExternalName
  externalName: api.core.svc
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: consul
  labels:
    name: consul
spec:
  ingressClassName: nginx
  rules:
  - host: consul.setyaji.my.id
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: consul
            port: 
              number: 80
