apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: "product.setyaji.my.id"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: product
            port:
              number: 80
  - host: "transaction.setyaji.my.id"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: transaction
            port:
              number: 80